extensions = ["md"]
timeout = 5 # in seconds
accept = [
    "200",
    "403", # TCG website blocks scrapper
    "502", # it's ok if the backend is down during the scan
    "503", # it's ok if the backend is down during the scan
]
exclude = []
